FROM snisioi/retele:2021

RUN apt-get update && apt-get install -y iptables iproute2 libnetfilter-queue-dev

RUN pip3 install --upgrade python-iptables cython
RUN pip3 install scapy
RUN pip3 install netfilterqueue

RUN mkdir -p /scripts
COPY src/*.sh /scripts/
COPY src/middle/arp_spoofing_script.py /scripts